// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./schema.prisma",
  // migrations folder not used in flattened repo; omit to avoid path errors
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
